### ISSUE TITLE
errorCode=22 The response status is not successful, status=403

### ISSUE THREAD

**Issue by ayeteng** [sdvcrx/pan-baidu-download#45]
下載錯誤

https://github.com/acgotaku/BaiduExporter/issues/547

似乎需要aria2c 加上cookie在header
Cookie: BDUSS=xxxxxx

**Comment by ttimasdf** [comment]
现在又不用加cookie了。
日常抽风吧。

**Comment by aelmahmoudy** [comment]
@ttimasdf how to add BDUSS cookie to aria2c ?
