### ISSUE TITLE
Baidu Netdisk doesn't download

### ISSUE THREAD

**Issue by Borusarino** [sdvcrx/pan-baidu-download#48]
Hi. Yesterday everything worked correctly, but today, I don't know why, the files stopped adding to Baidu Netdisk and started downloading via google chrome. Does anybody know how can I fix this? I don't want tu use the google chrome downloader because it is too slow and I can't resume the download once it has stopped.

Thanks in advance.

**Comment by sdvcrx** [comment]
Hi. I just tested, it seems working fine. Could you please provide the Baidu Netdisk download link?

Or try this Chrome Extensions: https://github.com/acgotaku/BaiduExporter
