### ISSUE TITLE
请问可以用在树莓派上么？

### ISSUE THREAD

**Issue by carloswear** [sdvcrx/pan-baidu-download#49]
新手，刚刚起步

有简略的教程没

**Comment by sdvcrx** [comment]
树莓派可以直接用

更方便的做法是在电脑安装 https://github.com/acgotaku/BaiduExporter ，树莓派启动 aria2 rpc

**Comment by carloswear** [comment]
谢谢~确定能用的话我就去做了，折腾的过程挺有趣的哈哈

**Comment by carloswear** [comment]
感谢！！
